---
- name: Create EC2 instances
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    vpc_subnet_id: "{{ random_subnet }}"
    security_group: "{{ instance_name }}-sg"
    wait: yes
    tags:
      Name: jumpbox
      EnvName: Test Environment
    exact_count: 1
    network:
       assign_public_ip: true
  register: ec2