- name: Create Security Group
  ec2_group:
    name: "{{ instance_name }}-sg"
    description: Security Group for {{ instance_name }}
    vpc_id: "{{ vpc_id }}"
    region: "{{ region_name }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ ipify_public_ip }}/32"
        rule_desc: "allows HTTP traffic from {{ ipify_public_ip }}"
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ ipify_public_ip }}/32"
        rule_desc: "allows SSH traffic from {{ ipify_public_ip }}"
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
